---

- name: Actions | Managing custom zabbix actions
  become: "{{ zabbix_server_config_become_on_localhost }}"
  delegate_to: localhost
  zabbix_action:
    server_url: "{{ zabbix_server_config_url }}"
    login_user: "{{ zabbix_server_config_api_user }}"
    login_password: "{{ zabbix_server_config_api_pass }}"
    name: "{{ item.name }}"
    event_source: "{{ item.event_source }}"
    state: "{{ item.state }}"
    status: "{{ item.status }}"
    esc_period: "{{ item.esc_period }}"
    default_subject: "{{ item.default_subject }}"
    default_message: "{{ item.default_message }}"
    recovery_default_subject: "{{ item.recovery_default_subject }}"
    recovery_default_message: "{{ item.recovery_default_message }}"
    conditions: "{{ item.conditions }}"
    operations: "{{ item.operations }}"
    recovery_operations: "{{ item.recovery_operations }}"
  with_items: "{{ zabbix_server_config_custom_actions }}"