---

- name: Templates | Create zabbix template # This module requires at least Ansible 2.9
  become: "{{ zabbix_server_config_become_on_localhost }}"
  delegate_to: localhost
  zabbix_template:
    server_url: "{{ zabbix_server_config_url }}"
    login_user: "{{ zabbix_server_config_api_user }}"
    login_password: "{{ zabbix_server_config_api_pass }}"
    validate_certs: "{{ zabbix_server_config_validate_certs | default(omit) }}"
    template_xml: "{{ item }}"
    state: present
  with_file: "{{ zabbix_server_config_custom_templates_xml }}"