---

- name: Dependencies | Installing the zabbix-api package on localhost
  delegate_to: localhost
  become: "{{ zabbix_server_config_become_on_localhost }}"
  pip:
    name: zabbix-api
    state: present
  register: zabbix_api_package_installed
  until: zabbix_api_package_installed is succeeded
