---

- name: "Installing the zabbix-api package on localhost"
  pip:
    name: zabbix-api
    state: present
  register: zabbix_api_package_installed
  until: zabbix_api_package_installed is succeeded
  delegate_to: localhost
  become: "{{ zabbix_server_config_become_on_localhost }}"

- name: "Create zabbix template" # This module requires at least Ansible 2.9
  zabbix_template:
    server_url: "{{ zabbix_server_config_url }}"
    login_user: "{{ zabbix_server_config_api_user }}"
    login_password: "{{ zabbix_server_config_api_pass }}"
    validate_certs: "{{ zabbix_server_config_validate_certs | default(omit) }}"
    template_xml: "{{ item }}"
    state: present
  become: "{{ zabbix_server_config_become_on_localhost }}"
  delegate_to: localhost
  with_file: "{{ zabbix_server_config_custom_templates_xml }}"
