---

- name: 'Create a script mediatype'
  zabbix_mediatype:
    name: 'Telegram'
    server_url: "{{ zabbix_server_config_url }}"
    login_user: "{{ zabbix_server_config_api_user }}"
    login_password: "{{ zabbix_server_config_api_pass }}"    
    type: 'script'
    status: enabled
    state: present
    script_name: 'telegram.py'
    script_params:
      - '{ALERT.SENDTO}'
      - '{ALERT.SUBJECT}'
      - '{ALERT.MESSAGE}'
  become: "{{ zabbix_server_config_become_on_localhost }}"
  delegate_to: localhost
