---

- name: Mediatypes | Setting mediatype notification script
  template:
    src: "{{ item.script_src }}"
    dest: "{{ zabbix_server_config_alertscript_path }}/{{ item.script_name }}"
    owner: zabbix
    group: zabbix
    mode: 0750
  with_items: "{{ zabbix_server_config_custom_mediatypes }}"

- name: Mediatypes | Managing Zabbix custom mediatypes
  become: "{{ zabbix_server_config_become_on_localhost }}"
  delegate_to: localhost
  zabbix_mediatype:
    server_url: "{{ zabbix_server_config_url }}"
    login_user: "{{ zabbix_server_config_api_user }}"
    login_password: "{{ zabbix_server_config_api_pass }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    status: "{{ item.status }}"
    script_name: "{{ item.script_name }}"
    script_params: "{{ item.script_params }}"
    state: "{{ item.state }}"
  with_items: "{{ zabbix_server_config_custom_mediatypes }}"
